import { z } from "zod";

const objectIdRegex = /^[0-9a-fA-F]{24}$/;

const localizedSchema = () =>
    z.object({
        en: z.string().min(1, "required"),
        ar: z.string().optional(),
    });

// Using z.unknown() for safer piping
const toNumber = z.preprocess((val) => {
    if (val === "" || val === undefined || val === null) return undefined;
    const num = Number(val);
    return isNaN(num) ? val : num;
}, z.unknown());

const toBoolean = z.preprocess((val) => {
    if (val === "true" || val === true) return true;
    if (val === "false" || val === false) return false;
    return val;
}, z.unknown());

const importProductRowSchema = z.object({
    _id: z.string().regex(objectIdRegex).optional(),
    productId: z.string().regex(objectIdRegex).optional(),
    productTag: z.string().trim().min(1).optional(),
    titleEn: z.string().trim().optional(),
    titleAr: z.string().trim().optional(),
    descriptionEn: z.string().trim().optional(),
    descriptionAr: z.string().trim().optional(),
    category: z.string().trim().optional(),
    categoryId: z.string().regex(objectIdRegex).optional(),
    price: z.union([z.string(), z.number()]).optional(),
    originalPrice: z.union([z.string(), z.number()]).optional(),
    discount: z.union([z.string(), z.number()]).optional(),
    remainingPieces: z.union([z.string(), z.number()]).optional(),
    variant: z.string().trim().optional(),
    isNewArrival: z.union([z.string(), z.boolean()]).optional(),
    isFeatured: z.union([z.string(), z.boolean()]).optional(),
    photo: z.string().trim().optional(),
    images: z.union([z.string(), z.array(z.string())]).optional(),
}).passthrough();

/**
 * Schemas
 */

// `slug` is auto-generated by a pre-save hook on Product. `rating` and `reviewCount`
// are synced from the Review model. None should ever come from client input.
// `.strict()` enforces the whitelist.
export const createProductSchema = z.object({
    body: z.object({
        productTag: z.string().trim().min(1).optional(),
        title: localizedSchema(),
        description: localizedSchema().optional(),
        category: z.string().regex(objectIdRegex, "invalid_id"),
        price: toNumber.pipe(z.number().positive()),
        originalPrice: toNumber.pipe(z.number().positive()).optional(),
        discount: toNumber.pipe(z.number().min(0)).optional(),
        variant: z.string().optional(),
        remainingPieces: toNumber.pipe(z.number().min(0)).optional(),
        isNewArrival: toBoolean.pipe(z.boolean()).optional(),
        isFeatured: toBoolean.pipe(z.boolean()).optional(),
    }).strict(),
});

export const updateProductSchema = z.object({
    body: z.object({
        productTag: z.string().trim().min(1).optional(),
        title: localizedSchema().partial().optional(),
        description: localizedSchema().partial().optional(),
        category: z.string().regex(objectIdRegex).optional(),
        photo: z.string().optional(),
        images: z.array(z.string()).optional(),
        price: toNumber.pipe(z.number().positive()).optional(),
        originalPrice: toNumber.pipe(z.number().positive()).optional(),
        discount: toNumber.pipe(z.number().min(0)).optional(),
        variant: z.string().optional(),
        remainingPieces: toNumber.pipe(z.number().min(0)).optional(),
        isNewArrival: toBoolean.pipe(z.boolean()).optional(),
        isFeatured: toBoolean.pipe(z.boolean()).optional(),
        isArchived: toBoolean.pipe(z.boolean()).optional(),
    }).strict().refine((data) => Object.keys(data).length > 0, { message: "empty_update" }),
});

export const importProductsSchema = z.object({
    body: z.object({
        products: z.array(importProductRowSchema).min(1),
    }).strict(),
});

export const updateStockSchema = z.object({
    body: z.object({
        quantity: toNumber.pipe(
            z.number()
                .int("invalid_format")
                .min(0, "non_negative")
        ),
        isAddition: toBoolean.pipe(z.boolean()).default(false),
    }).strict(),
});
