import { z } from 'zod';
import { CategoryType } from './category.types';

const objectIdRegex = /^[0-9a-fA-F]{24}$/;

const localizedStringSchema = z.object({
    en: z.string().min(1, { message: "errors.validations.required" }),
    ar: z.string().optional(),
});

const normalizeCategoryBody = (body: unknown) => {
    if (!body || typeof body !== "object") return body;

    const raw = body as Record<string, unknown>;
    const normalized: Record<string, unknown> = { ...raw };

    if (!normalized.name && (raw["name[en]"] || raw["name[ar]"])) {
        normalized.name = {
            en: raw["name[en]"],
            ar: raw["name[ar]"],
        };
    }

    if (!normalized.description && (raw["description[en]"] || raw["description[ar]"])) {
        normalized.description = {
            en: raw["description[en]"],
            ar: raw["description[ar]"],
        };
    }

    delete normalized["name[en]"];
    delete normalized["name[ar]"];
    delete normalized["description[en]"];
    delete normalized["description[ar]"];

    return normalized;
};

/**
 * Reusable helper to handle empty strings from multipart/form-data
 */
const parentCategorySchema = z.preprocess(
    (val) => (val === "" || val === "null" || val === undefined ? undefined : val),
    z.string().regex(objectIdRegex, "errors.validations.invalid_id").optional()
);

// `slug` is auto-generated by a pre-save hook; never accept from client.
export const createCategorySchema = z.object({
    body: z.preprocess(normalizeCategoryBody, z.object({
        name: localizedStringSchema,
        description: localizedStringSchema.optional(),
        type: z.nativeEnum(CategoryType, { message: "errors.validations.invalid_enum" }),
        parentCategory: parentCategorySchema,
        thumbnail: z.string().optional(),
    }).strict()).refine((data) => {
        // If type is category, parentCategory must be empty/undefined
        if (data.type === CategoryType.CATEGORY) {
            return !data.parentCategory;
        }
        // If type is subCategory, parentCategory must be a valid ID
        if (data.type === CategoryType.SUB_CATEGORY) {
            return !!data.parentCategory;
        }
        return true;
    }, {
        message: "errors.validations.category.invalid_hierarchy",
        path: ["parentCategory"],
    }),
});

export const updateCategorySchema = z.object({
    params: z.object({
        id: z.string().regex(objectIdRegex, "errors.validations.invalid_id")
    }),
    body: z.preprocess(normalizeCategoryBody, z.object({
        name: localizedStringSchema.partial().optional(),
        description: localizedStringSchema.partial().optional(),
        type: z.nativeEnum(CategoryType).optional(),
        parentCategory: parentCategorySchema,
        thumbnail: z.string().optional(),
    }).strict()).refine((data) => {
        // Validation for type switching or partial updates
        if (data.type === CategoryType.CATEGORY && data.parentCategory) {
            return false;
        }
        if (data.type === CategoryType.SUB_CATEGORY && !data.parentCategory) {
            return false;
        }
        return true;
    }, {
        message: "errors.validations.category.invalid_hierarchy",
        path: ["parentCategory"],
    }),
});
